### ISSUE TITLE
easy installation?

### ISSUE THREAD

**Issue by mikeopensauce** [saschaludwig/OnAirScreen#11]
Hi,
I love the idea of this clock. The features list "easy installation" but I can't find any instructions for installation anywhere.
Please could somebody post some as I've spent about an hour trying to get this up and running so far and seem to fix one problem followed by another over and over again.
A simple step by step would be really handy.
Many thanks
MIke

**Comment by shortyxs** [comment]
Well, I ran into something similar.
For a Raspberry PI I put together some basic steps. 
https://gist.github.com/shortyxs/e9fa6265e6574559d5fa98afab798576

Never the less, I might missed something, also I struggled in sending UDP commands from Windows to my Pi.
Not figured that out yet.

**Comment by mikeopensauce** [comment]
Thanks very much. I can now send udp commands from the Linux command line but I'm struggling to send them from a local webserver as I want to convert a web request to a UDP message e.g. when our phone is ringing.

**Comment by saschaludwig** [comment]
Hi, thanks @shortyxs for putting together a small help and for answering.
@mikeopensauce the next release of OnAirScreen will also have a http API. So you can do http requests with curl or wget or similar.
Parts of the new version are already in the python3_pyQt5 branch + a bunch of bugfixes and a customisable format for the date string. HTTP API is currently in testing and might get pushed to the branch in the next two weeks. I also considered  a commandline tool for linux/windows/mac to send commands to OnAirScreen instances but I don't know if that is on any use. Most of the radio automation systems I integrated could send UDP packets natively. For example Audisi GML, OmniPlayer, Rivendell, Wideorbit.
I also offer paid support for studios if you need some custom code for the integration of a radio automation system.

**Comment by saschaludwig** [comment]
@mikeopensauce the "easy installation" describes the usage process when using the precompiled binaries which are available as a paid version for mac/linux/windows. Even though there is a paid version of this available here https://www.astrastudio.de/software/onairscreen/ or through the contact form, all new features which were added for paying customers will be made available as source! And that will never change.
But due to my rather limited time, development of new features is sometimes only possible if someone pays for it :-)

**Comment by mikeopensauce** [comment]
Fair points as I appreciate you have to earn a living. Thanks for thd great product.
Mike

**Comment by saschaludwig** [comment]
@shortyxs @mikeopensauce The python3_pyQt5 branch now has an oas_send command line utility which can be used to send UDP API messages to an OnAirScreen instance under windows and all other platforms
