### ISSUE TITLE
Cannot load the programme at all now?

### ISSUE THREAD

**Issue by KyleRickards** [saschaludwig/OnAirScreen#13]
Hi

I have just downloaded the new version, at first I got this error:

Thanks for this - I am getting the following error when trying to to install ntplib

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-KyuOh6/ntplib/

WHich means that the main ./start.py does not work for me and I can't use the programme anymore :(

EDIT: Full text

Collecting ntplib
Using cached https://files.pythonhosted.org/packages/29/8b/85a86e01c510665b0790d3a9fd4532ad98aba9e185a676113a0ae3879350/ntplib-0.3.3.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in
ImportError: No module named setuptools

However, I think I have fixed the NTP issue but now I am getting this error:

./start.py
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
File "./start.py", line 958, in
mainscreen = MainScreen()
File "./start.py", line 71, in **init**
app.setOverrideCursor( QCursor( 10 ) );
TypeError: QCursor(): argument 1 has unexpected type 'int'

**Comment by saschaludwig** [comment]
Please do NOT rum beta versions in a production environment.
Always test on a different VM or machine.

It looks like you checked out the wrong version and probably using the wrong python version as well.
There is no line 71 in start.py with `app.setOverrideCursor( QCursor( 10 ) );` in the current one.
Looks like you still use the master branch.
Latest is in python3_pyQt5.
It is also advised to run python software in a virtual environment, so you don't break your system python and/or it's dependencies. A detailed howto on virtualenv can be found here: https://docs.python-guide.org/dev/virtualenvs/
Also please try to use pip3 packages instead of manual installations.

**Comment by KyleRickards** [comment]
Hi
I'm so confused, I'm sorry I don't really understand Python and the dependencies.
I have deleted all the stuff I have and have downloaded the version in python3_pyQt5. I am trying to make this version and I get the following error.
make
pyuic5 mainscreen.ui -o mainscreen.py
make: pyuic5: Command not found
Makefile:4: recipe for target 'mainscreen.py' failed
make: *** [mainscreen.py] Error 127


I realise that you have other work to do and I appreciate the fact that you have helped me this far.
Kyle


    On Wednesday, 6 February 2019, 10:53:33 GMT, Sascha Ludwig <notifications@github.com> wrote:  
 
 
Please do NOT rum beta versions in a production environment.
Always test on a different VM or machine.

It looks like you checked out the wrong version and probably using the wrong python version as well.
There is no line 71 in start.py with app.setOverrideCursor( QCursor( 10 ) ); in the current one.
Looks like you still use the master branch.
Latest is in python3_pyQt5.
It is also advised to run python software in a virtual environment, so you don't break your system python and/or it's dependencies. A detailed howto on virtualenv can be found here: https://docs.python-guide.org/dev/virtualenvs/
Also please try to use pip3 packages instead of manual installations.

**Comment by KyleRickards** [comment]
Hi
I don't think I was running a beta version, I was using the Main one?
I have checked my python installation and I now have 3.5.2 running. I have downloaded the python3_pyQt5 version and still I cannot get it working so for now I will have to stop using it.
I don't use manual installs, I usually do the Make command and then ./start.py.  This is all different to me and I am completely confused.

Thank you for your help though.
Kyle

    On Wednesday, 6 February 2019, 10:53:33 GMT, Sascha Ludwig <notifications@github.com> wrote:  
 
 
Please do NOT rum beta versions in a production environment.
Always test on a different VM or machine.

It looks like you checked out the wrong version and probably using the wrong python version as well.
There is no line 71 in start.py with app.setOverrideCursor( QCursor( 10 ) ); in the current one.
Looks like you still use the master branch.
Latest is in python3_pyQt5.
It is also advised to run python software in a virtual environment, so you don't break your system python and/or it's dependencies. A detailed howto on virtualenv can be found here: https://docs.python-guide.org/dev/virtualenvs/
Also please try to use pip3 packages instead of manual installations.

**Comment by KyleRickards** [comment]
Ok, I don't know how I managed it but the system is up and running again - I cannot see the action to change the language though?
KYle

**Comment by saschaludwig** [comment]
Okay if you wanted to use the main (old version): nothing changed there since years.
The old version needs python2 and pyQt4. The newest beta version tagged "0.9beta2" needs pyqt5 and python3.

> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-KyuOh6/ntplib/

Because of that I thought you tried to download and install ntplib manually. Sorry, misinterpreted that.

easiest and safest way to run the new beta version would be:
`pip3 install virtualenv`
then inside the OnAirScreen directory: `virtualenv venv` to initialize a new virtual python environment into the directory "venv" (will be created).
`source venv/bin/activate` to activate the newly created virtual environment.
from here you can now use `pip install -r requirements.txt` which will automagically install all needed requirements.
`make && ./start.py` should do the rest and start ne newest version.

But remember to activate the virtual environment again if you want to start it in a new shell.

Hope that helped a bit.
If you don't want to mess around with navigating through the whole python stuff: I also offer precompiled binaries including updates for Windows/Linux/MacOS for 15€ on my website. See readme.md

Best regards
Sascha

**Comment by saschaludwig** [comment]
> Ok, I don't know how I managed it but the system is up and running again - I cannot see the action to change the language though? KYle

Glad you managed fix the problem somehow.
What version do you see when you open the Settings->About Tab?
Should say 0.9beta2. Otherwise you are still running the old version.

**Comment by KyleRickards** [comment]
Hi
It says 0.7 so I am guessing that's the old one still? I tried a newer one and that didn't seem to work for me?

    On Wednesday, 6 February 2019, 16:37:16 GMT, Sascha Ludwig <notifications@github.com> wrote:  
 
 

Ok, I don't know how I managed it but the system is up and running again - I cannot see the action to change the language though? KYle


Glad you managed fix the problem somehow.
What version do you see when you open the Settings->About Tab?
Should say 0.9beta2. Otherwise you are still running the old version.

**Comment by KyleRickards** [comment]
Hi
Just tried the 0.9beta2 and I'm getting errors again so I must be doing something wrong.
Thank you for taking time to help me with this, I shall just have to buy the one from the website.
Many thanksKyle

    On Wednesday, 6 February 2019, 16:37:16 GMT, Sascha Ludwig <notifications@github.com> wrote:  
 
 

Ok, I don't know how I managed it but the system is up and running again - I cannot see the action to change the language though? KYle


Glad you managed fix the problem somehow.
What version do you see when you open the Settings->About Tab?
Should say 0.9beta2. Otherwise you are still running the old version.

**Comment by saschaludwig** [comment]
@KyleRickards what errors do you get? did you try create a virtualenv?

**Comment by KyleRickards** [comment]
Hi
I did run install and run the virtual environment to test the version you suggested but it gave me errors - I can switch machines and replicate it again to get the error messages. One minute.
ThanksKyle

    On Thursday, 7 February 2019, 13:14:24 GMT, Sascha Ludwig <notifications@github.com> wrote:  
 
 
@KyleRickards what errors do you get? did you try create a virtualenv?

**Comment by KyleRickards** [comment]
Hi Sascha
Ok, this is where I am up to with it (I have two separate hard drives running separate instances)
OnAir Screen (Master)
On Linux Mint 19.1 - the original version of OnAirScreen will not work for me at all now. I can copy those messages separately.
On Linux Mint 18, the original version of OnAirScreen works fine but I can't remember what I changed to get it working. As per your other email, I have set up the virtual environment which seems to work. I have copied the above text below
 ~/OnAirScreen-python3_pyQt5 $ virtualenv venvRunning virtualenv with interpreter /usr/bin/python2
New python executable in /home/kyle/OnAirScreen-python3_pyQt5/venv/bin/python2
Not overwriting existing python script /home/kyle/OnAirScreen-python3_pyQt5/venv/bin/python (you must use /home/kyle/OnAirScreen-python3_pyQt5/venv/bin/python2)
Installing setuptools, pkg_resources, pip, wheel...done.

~/OnAirScreen-python3_pyQt5 $ source venv/bin/activate
(venv)  ~/OnAirScreen-python3_pyQt5 $ make && ./start.py
pyuic5 mainscreen.ui -o mainscreen.py
make: pyuic5: Command not found
Makefile:4: recipe for target 'mainscreen.py' failed
make: *** [mainscreen.py] Error 127

I don't know if that helps any? Also, when I run the reuirements thing I get the following error message:
pip install -r requirements.txt
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting PyQt5 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement PyQt5 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for PyQt5 (from -r requirements.txt (line 1))







    On Thursday, 7 February 2019, 13:14:24 GMT, Sascha Ludwig <notifications@github.com> wrote:  
 
 
@KyleRickards what errors do you get? did you try create a virtualenv?

**Comment by KyleRickards** [comment]
Hi
So on Linux 19, when I try and run the old version in a virtual environment I get this error:
make
pyuic4 mainscreen.ui -o mainscreen.py
Traceback (most recent call last):
  File "/usr/bin/pyuic4", line 3, in <module>
    import PyQt4.uic.pyuic
ImportError: No module named PyQt4.uic.pyuic
Makefile:4: recipe for target 'mainscreen.py' failed
make: *** [mainscreen.py] Error 1


Without doing it in a virtual environment, I get this error:
./start.py
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "./start.py", line 958, in <module>
    mainscreen = MainScreen()
  File "./start.py", line 71, in __init__
    app.setOverrideCursor( QCursor( 10 ) );
TypeError: QCursor(): argument 1 has unexpected type 'int'


So I am completely baffled because the old version works on one OS but not the other and the latest 0.9beta doesn't work on any?

**Comment by KyleRickards** [comment]
Well, it's working but I have no idea how I got it working?!
Maybe downloaded some QT5 files that were missing?

**Comment by saschaludwig** [comment]
You just found a bug.
The `TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'` error is now fixed in the latest commit 054cd18dec9bb81eb65b6e1f7b39246bee450055
