### ISSUE TITLE
Settings Screen Not Opening on Compiled Mac Version

### ISSUE THREAD

**Issue by mobbyg** [saschaludwig/OnAirScreen#14]
OS: macOS Mojave v10.14.2

Using the Beta version, Python3 and QT5, used the build shell script for Mac OSX. 
App built and runs, but when trying to bring up the Settings using the CTRL+S or CTRL+, keys, nothing happens. All the other key combos seem to work as described in the Readme.md

**Comment by saschaludwig** [comment]
On OSX you have to use the "Command ⌘" Key + s/,

**Comment by mobbyg** [comment]
Yep, the CMD+S key worked. Thank you.
