### ISSUE TITLE
python3_pyQt5_http: Raspbian SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by plche** [saschaludwig/OnAirScreen#16]
As per instructions [here](https://github.com/saschaludwig/OnAirScreen/issues/13#issuecomment-461090353) and taking into account that escenario is Raspbian Stretch with python3 (3.5.3) venv activated and after:
1. Installed pyQT5 version (5.7.1+dfsg-3+rpi1+deb9u1) by:
    sudo apt-get install qt5-default pyqt5-dev pyqt5-dev-tools
2. Installed ntplib version (0.3.3) by:
    pip3 install ntplib
3. Installed PyInstaller==3.4 by:
    pip3 install PyInstaller==3.4
4. make && ./start.py
gets the following:
File "./start.py", line 60
   getTimeWindow: QDialog
                             ^
SyntaxError: invalid syntax
Why? How can fix it?

**Comment by saschaludwig** [comment]
What branch and which version/commit are you using?
Installing the requirements in your system does not help. You have to install them in your virtual environment as shown in the instructions you actually linked. What was the cause you did 1-3?
It seems you also have general problem with your python interpreter.

what does
`which python` and ` /usr/bin/env python3 --version`
output? It looks the script was actually interpreted by bash, not by python.

**Comment by plche** [comment]
Clonned Branch: python3_pyQt5_http

System (terminal output from `cat /etc/os-release` command):
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

What was the cause you did 1-3?
When trying `pip install -r requirements.txt` gave me the following error:
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting PyQt5 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement PyQt5 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for PyQt5 (from -r requirements.txt (line 1))

Output for `which python`:
/home/pi/OnAirScreen/venv/bin/python

Output for `/usr/bin/env python3 --version`:
Python 3.5.3

Thanks in advance for your support.

**Comment by saschaludwig** [comment]
The pip in your distribution might have a bug. According to [PEP426](https://www.python.org/dev/peps/pep-0426/#name):
```
All comparisons of distribution names MUST be case insensitive,
and MUST consider hyphens and underscores to be equivalent.
```
try to switch case in requirements.txt `pyQt5 -> pyqt5`

Please also try a `which pip` to see where pip actually comes from. Maybe the virtualenv was not activated properly by some strange behavior and it is using the system pip which could be python2.7 or something else.

**Comment by plche** [comment]
![image](https://user-images.githubusercontent.com/30966796/53704951-02810a00-3def-11e9-9cf0-c94465d0e164.png)

**Comment by plche** [comment]
![image](https://user-images.githubusercontent.com/30966796/53705014-6572a100-3def-11e9-8334-5401a7e14ac4.png)
Output when switching case in requirements.txt pyQt5 -> pyqt5

**Comment by saschaludwig** [comment]
Ah okay, my fault: Should have checked that upfront:
https://pypi.org/simple/pyqt5/

The pypi.org/simple repository does not have pyQt5 for your platform. (arm)
Looks like you need to build pyqt5 from [source](http://pyqt.sourceforge.net/Docs/PyQt5/installation.html#building-and-installing-from-source)
or install the requirements in your system, which is generally not a good idea as it might break your default system python if you don't know what you are doing.

**Comment by plche** [comment]
Installing requirements in my system leads to original post error...
So, what would be the solution in order to fix that syntaxerror?

**Comment by saschaludwig** [comment]
As I mentioned earlier: It looks like the file is not executed with the correct python version.
You could change your default python or remove old python versions completely. But again: that is not a good idea if you don't know what you are doing ;-)
Please try to understand how your distribution handles different python versions and where their libraries are stored.
Sorry I won't point out a command which will destroy someones default python installation on their system.
I would suggest to build pyqt5 inside the virtualenv. Please find link in my previous comment.

**Comment by plche** [comment]
Dear Sascha,
I follow your recommendation and installed PyQt5 inside the virtualenv from the [source](http://pyqt.sourceforge.net/Docs/PyQt5/installation.html#building-and-installing-from-source), also to avoid missconfigs with python, I make a clean Raspian Strech installation, but syntaxerror (invalid syntax) continues, please take a look at my settings in the following picture:
![image](https://user-images.githubusercontent.com/30966796/53990633-b5ef4480-40f6-11e9-9ef2-1a2940c7a07b.png)
What's wrong then?, is there a chance to get your code compiled for Raspberry?, do you know if anybody has been succeeded at doing it?
Thanks in advance for your kindly attention.
-Percy

**Comment by saschaludwig** [comment]
Hm, python 3.5 is quite old. Even though 3.5 should support type hints, maybe you could try to update to a recent python version like 3.7.
And yes it runs on Raspberrys. I sell them as hardware appliance with OnAirScreen on it :)

**Comment by plche** [comment]
I can confirm what you mentioned about python 3.5, I upgraded to 3.7.2 and it worked!
Thank you so much Sascha, will close now this issue.
