### ISSUE TITLE
Trigger lights with switch

### ISSUE THREAD

**Issue by mikeopensauce** [saschaludwig/OnAirScreen#18]
Anyone worked out a way to trigger the mic live light from a switch? E.g. the fader switch on my mixer. 
Something like connecting to a serial port would be handy.
Many thanks
Mike

**Comment by saschaludwig** [comment]
It's done via UDP packets to the OnAirScreen API.
Cheapest way would be to hook up an Arduino or ESP8266 to the switch and send UDP packets (LED1:ON or LED1:OFF) to the OnAirScreen IP whenever the switch state changes. Costs below $5

**Comment by mikeopensauce** [comment]
Thanks for the advice Sascha

Mike

Mike Cox
Managing Director
The Rosetta Group Ltd

Email: mike@rosetta.group
Website: www.rosetta.group<http://www.rosetta.group>
Phone: 03 004 004 004

￼

Have a look at our new cloud phone system at www.rosettatelecom.com<http://www.rosettatelecom.com>
See our payment options and pay online by clicking here Pay online

________________________________
