### ISSUE TITLE
UDP Multicast Remote Option?

### ISSUE THREAD

**Issue by MC42** [saschaludwig/OnAirScreen#19]
Currently working on a project where I might need to control an arbitrary number of OAS boxes on the same network, and rather than have to store IPs / set statics, would it be possible to get a UDP multicast listener as well as the standard UDP listener, on a different port maybe?

**Comment by saschaludwig** [comment]
As far as I remember, OAS will already react to UDP broadcast messages, so all OAS boxes within the same physical/logical network will react to commands.
But I keep that multicast listener in mind! That's quite a nice idea.

**Comment by saschaludwig** [comment]
Finally, that Multicast Group Join is happening in the "multicast" branch and will hopefully be included in version 0.9.6

**Comment by saschaludwig** [comment]
implemented in #53
