### ISSUE TITLE
Does not install

### ISSUE THREAD

**Issue by itconor** [saschaludwig/OnAirScreen#22]
Current Code Will not install Requirements .txt will not install on ubuntu 18.04 on x86

manually installing the required PyQt5 Will let me compile but running just errors out with this

  from PyQt5 import QtWebEngineWidgets
ImportError: cannot import name 'QtWebEngineWidgets'

From what i could see QtWebEngineWidgets is no longer supported under PyQt5 and requires updates to the code 
Documentation seems to be nonexistent

**Comment by saschaludwig** [comment]
Please use the latest branch. [https://github.com/saschaludwig/OnAirScreen/tree/weatherwidget](url)
