### ISSUE TITLE
Setting up On Air Screen

### ISSUE THREAD

**Issue by mystame** [saschaludwig/OnAirScreen#29]
I have seen this software being used at a charity radio station (we brought it for use there), but wanted to use it in my home studio on a Raspberry Pi 2, but have been having some issues getting it to behave and remember the settings I would like it to have...

I have created clean instance of Raspbian and updated many times now.

This from terminal upon loading for the first time

- pi@StudioClock:~/OnAirScreen $ ./start.py
- libEGL warning: DRI2: failed to authenticate
- qt5ct: using qt5ct plugin
- QFSFileEngine::open: No file name specified
- Weather: 01d None
- update weather called
- OWM API Call
- Loading Settings from:  /home/pi/.config/astrastudio/OnAirScreen.conf
- Error occured: 204, Host requires authentication
- NTP Check triggered
- entered CheckNTPOffsetThread.run
- NTP error: No response received from pool.ntp.org.
- Quitting, cleaning up...
- pi@StudioClock:~/OnAirScreen $

If I try to reload without making any changes to station name etc it loads, however if i make any changes then I get the following:

- pi@StudioClock:~/OnAirScreen $ ./start.py
- libEGL warning: DRI2: failed to authenticate
- qt5ct: using qt5ct plugin
- QFSFileEngine::open: No file name specified
- Weather: 01d None
- update weather called
- OWM API Call
- Traceback (most recent call last):
-   File "./start.py", line 1263, in <module>
-     main_screen = MainScreen()
-   File "./start.py", line 70, in __init__
-     self.restore_settings_from_config()
-   File "./start.py", line 644, in restore_settings_from_config
-     self.buttonLED1.setVisible(settings.value('used', True))
- TypeError: setVisible(self, bool): argument 1 has unexpected type 'str'

For peace of my own mind, these are the steps I'm taking to get the system ready to run OnAirScreen:

- sudo apt update
- sudo apt full-upgrade
- reboot raspberry pi
- 
- sudo su
- apt install neofetch git
- echo neofetch >> /etc/bash.bashrc
- echo net.ipv6.conf.all.disable_ipv6 = 1 >> /etc/sysctl.conf
- sysctl -p
- 
- apt-get install qt5-default pyqt5-dev pyqt5-dev-tools
- exit
- pip3 install ntplib
- pip3 install PyInstaller
- 
- git clone https://github.com/saschaludwig/OnAirScreen
- cd OnAirScreen
- make
- ./start.py

Please can you offer any help/guidance for what is not working as expected? Thanks in advance...

**Comment by saschaludwig** [comment]
That sounds like an old bug I thought I had fixed.
Could you attach the config file which will be written to
`/home/pi/.config/astrastudio/OnAirScreen.conf`
in your case?

And please supply the version you are running with:
`git rev-parse --verify HEAD`

**Comment by saschaludwig** [comment]
I already found it. That bug was introduced in one of the last commits and only occurs on platforms that use .ini style config files in Qt. Now fixed in 26287e6f9b761cbf45f63f71b72b28b12af016e5

**Comment by saschaludwig** [comment]
Please reopen if not fixed :)

**Comment by mystame** [comment]
Thank you, its working as expected now :)
