### ISSUE TITLE
1 second out

### ISSUE THREAD

**Issue by st1nga** [saschaludwig/OnAirScreen#3]
I note that the time is exactly 1 second out compared to my desktop time.
I suspect it is moving the second hand (or dot) too soon.. maybe...

**Comment by st1nga** [comment]
It is +1 second.

I am also getting the `Clock NTP status unknown error` message at start up.
I saw a reference to an issue:

> The "Clock not NTP syncronized" error shows when your local clock differs too much from the ptbtime1.ptb.de server or when no ntp server is set to compare the local clock to. You can set an NTP server in the settings. See the readme.md for keyboard shortcuts

But searching the code I don't see `ptbtime1.ptb.de` mentioned

How does it check?

**Comment by saschaludwig** [comment]
Hi

https://github.com/saschaludwig/OnAirScreen/blob/master/start.py#L766

There is the NTP check function, and when the local clock differs more than 300ms from one of the NTP servers from pool.ntp.org or if the check is not possible it will spit out the warning messages.

I had used ptbtime1 in the past, but changed it at some point. Sorry for the confusion.

Are you checking the display time of the OnAirScreen against the commandline "date" command?
I realized that KDE & Gnome had +/- delays all the time and are not really showing seconds in sync with the system clock.

Maybe there is a flaw in the code at some place I can not imagine right now.
But in the worst case the displayed time should only differ 100ms from system time as the self.constantUpdate timer is set to 100ms in https://github.com/saschaludwig/OnAirScreen/blob/master/start.py#L106

**Comment by st1nga** [comment]
Turns out the time is correct with
`while true; do date; done`
The task bar is slow by 1 second.

So that just leaves the `Clock NTP status unknown error` message...

So I found:
`mike@shark:~/OnAirScreen$ find . -type f -exec grep wr-fw {} \; -ls
        self.NTPCheckServer.setText(settings.value('ntpcheckserver', 'wr-fw').toString())
108670675     24 -rw-r--r--   1 mike     users       23072 Jun  7 13:34 ./settings_functions.py
        ntpserver = str(settings.value('ntpcheckserver', 'wr-fw').toString())
108670343     40 -rwxr-xr-x   1 mike     users       40855 Jun  7 13:24 ./start.py
Binary file ./settings_functions.pyc matches
108699005     24 -rw-r--r--   1 mike     users       21425 Jun  7 13:35 ./settings_functions.pyc
``
and you can see I have changed them. wr-fw is my firewall offering ntp time which in turn is synced to am upstream server somewhere, can't remember off hand.

Since both are using the same server I would have thought the message is impossible unless it does not understand what is returned or it is not answering.
More investigation required.....

**Comment by st1nga** [comment]
I just changed it to another host on my network, that does not offer ntp on port 123 and I am not seeing any data over the network to port 123, which is odd.

**Comment by saschaludwig** [comment]
If you run ./start.py from a terminal, does the debug output give any clue what is happening?
The function at https://github.com/saschaludwig/OnAirScreen/blob/master/start.py#L766
has several prints which should give you a hint what is happening.
Upon start it checks every 5 seconds if the time is syncronized, once it gets a positive result (<300ms offset), the check is repeated every 60 seconds.

**Comment by st1nga** [comment]
So using sulaco which does not offer NTP I got an error:

```
mike@shark:~/OnAirScreen$ ./start.py
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
error checking NTP sulaco.wolf-rock.com
```
But I still did not see anyting

**Comment by st1nga** [comment]
OK, I don't think it checks straight away, it looks like it pops the message up and then checks some seconds after, it may not, but that is what it looks like.
(sulaco was unresolvable :-) )

**Comment by saschaludwig** [comment]
It looks like the supplied NTP server isn't existent:

    sl@dev:~$ host sulaco.wolf-rock.com
    Host sulaco.wolf-rock.com not found: 3(NXDOMAIN)

**Comment by saschaludwig** [comment]
Yes the check is done every 5 seconds in case of an error or an unknown state. With a 5 second initial delay after startup. And the displayed error message means exactly what it says :-D
"NTP status unknown" while not beeing checked in the first 5 seconds.

**Comment by saschaludwig** [comment]
You might want to change the external NTP check server "pool.ntp.org" to a more reliable list :-)
Or if you are 100% certain that your local NTP server is always correct, just enter the IP of that local NTP server in the config dialog under "NTP Check Server"

![Config Dialog](https://user-images.githubusercontent.com/12997980/41107152-f9b7aaa6-6a71-11e8-8b46-016c84941695.png)

**Comment by st1nga** [comment]
Ah, ok, so it is just an message that happens on start up :-)
