### ISSUE TITLE
Weather Widget Displays Wrong Temp Measurement

### ISSUE THREAD

**Issue by mobbyg** [saschaludwig/OnAirScreen#31]
In the latest master, after creating an account and activating the weather widget, when you change the unit of measure from Celsius to Fahrenheit or to Kelvin, and then hit the "Apply and Save" button, the widget itself on the main screen always shows Celsius. 
<img width="1722" alt="Screen Shot 2020-11-25 at 9 12 53 PM" src="https://user-images.githubusercontent.com/5174814/100300462-145ff480-2f64-11eb-9058-1d1de6e933a0.png">
<img width="1725" alt="Screen Shot 2020-11-25 at 9 19 18 PM" src="https://user-images.githubusercontent.com/5174814/100300469-17f37b80-2f64-11eb-80cc-68868d1fc857.png">

**Comment by saschaludwig** [comment]
Thank you for the report! That is indeed a bug :-)
Will fix that soon.

**Comment by mobbyg** [comment]
You're very welcome. I may have come across another an other issue with restarting the clock after changing the setting between 12/24 time. I'm going to install it separate from my Mac install so as not to cause an issue with the plist file, which is what happened before. And of course I'll have some info for documentation.

**Comment by saschaludwig** [comment]
Fixed in https://github.com/saschaludwig/OnAirScreen/commit/0f0bf0ee5de318e41487dafd170bee2ac550484e
