### ISSUE TITLE
Current Version not running after building on MacOS with Pyinstaller

### ISSUE THREAD

**Issue by mobbyg** [saschaludwig/OnAirScreen#33]
I've been able to successfully build the previous version and run it, with the incorrect temp measurement, with no issues. But trying to run after building with the newest, causes the icon on the dock to appear and then disappear. I get the following error when trying to run it with 'open start.app' in a command line... 

LSOpenURLsWithRole() failed with error -10810 for the file /Users/kb2mob/zdir/OnAir Clock/OnAirScreen-master/dist/start.app

This is using pyinstaller 4.0 with Python 3.7, and PyQt5 on MacOS 10.15.7. I did have pyinstaller 4.1 and downgraded to see if that would allow me to build. I have downloaded the code again from here, and created fresh directories. Previously, I would double click the icon and it would start and them immediately crash. 
It didn't. I am using the following switches:

--clean -w -i oas_icon.icns start.py

I have been able to build on Windows 7 with same version of python and with pyinstaller 4.1. 
Not sure where to look to troubleshoot this further.

**Comment by saschaludwig** [comment]
Hi, it's not a python error message or an error from OnAirScreen.
Looks like a random Apple error.
Googling suggests it has something to do with a broken xcode installation. Or at least with some broken xcode commandline tools installation.
My first guess would have been: the app might have no permission to contact the openweathermap server.
Try to start the binary from the terminal directly, not with "open" and the app package to get more debug messages or any crash messages from python.

**Comment by saschaludwig** [comment]
Just tested the latest commit in my CI environment and all Platforms (Win 32, Win 64, Mac 10.12/12.13/10.14/10.15, Linux x86, Raspberry Pi OS x86) build and start successfully, so it might be a local problem.

**Comment by mobbyg** [comment]
OK, thanks. I'll reinstall XCode and see what I get. Thanks

**Comment by mobbyg** [comment]
It looks like it's a little more deeper than that. According to some others experiencing the same issue, MacOS moved the locations of the linked libraries in BigSur and this is causing issues. I have updated to XCode 12.3, Pyinstaller 4.1 and Python 3.9.1 and still have the same issues.

**Comment by saschaludwig** [comment]
I can run OnAirScreen on MacOS Big Sur so I don't see what I could fix. If Pyistaller is broken for you: don't use pyinstaller. Just use OnAirScreen as is ;-)

**Comment by mobbyg** [comment]
Figured it out. Needed to be signed.
