### ISSUE TITLE
start.py: cannot connect to X server

### ISSUE THREAD

**Issue by roelmeijer** [saschaludwig/OnAirScreen#36]

**Comment by roelmeijer** [comment]
Can you help me I get a start.py: cannot connect to X server?

**Comment by saschaludwig** [comment]
Looks like you started the program from a terminal where no X server ist present.
To help you I need more information on what system you use and how you tried to start it.

**Comment by roelmeijer** [comment]
Sascha,

Thanks for reaction! I haven fix the X server problem. Next error is:
I work on a Pi

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile

Traceback (most recent call last):
File "./start.py", line 958, in <module>
mainscreen = MainScreen()
File "./start.py", line 71, in __init__
app.setOverrideCursor( QCursor( 10 ) );
TypeError: QCursor(): argument 1 has unexpected type 'int'

Op ma 22 mrt. 2021 om 00:26 schreef Sascha Ludwig ***@***.***

**Comment by saschaludwig** [comment]
Hi, which platform/OS are you using and which version/commit of OnAirScreen did you checkout?
Which python and which Qt version?
Most recent is in the font_and_size branch. Last stable is master in  https://github.com/saschaludwig/OnAirScreen/commit/9a2168d2b0dd2b4e47769b9c037467e13164747a

**Comment by saschaludwig** [comment]
Looks like you are using a pretty old version.
The line "app.setOverrideCursor( QCursor( 10 ) );" isn't in the code since 05.01.2019.
That was indeed a bug and was fixed since then.

**Comment by roelmeijer** [comment]
Hi Sascha,

I start from a clean Pi and its working now. Thanks for the time!

Roel

Op ma 22 mrt. 2021 om 15:27 schreef Sascha Ludwig ***@***.***
