### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by sqpp** [saschaludwig/OnAirScreen#4]
Hey, whatever I do, whenever I start the start.py on Ubuntu this appears.

Do you have any clue what is wrong?
![image](https://user-images.githubusercontent.com/27697736/41673279-c3880e1c-74bc-11e8-8a71-5023536558ab.png)

**Comment by saschaludwig** [comment]
Hi

settings.py and other .py files are just modules used by the OnAirScreen. They can't be called directly. The only file with executable permissions should be start.py.

Which PyQt version did you install?
Qt.BlankCursor is defined to be (int) 10. So that line should replace the cursor with the blank one (no cursor)

**Comment by sqpp** [comment]
Hi!

Yeah, actually just tested if that would work  :DDD 

I used PyQt4 cause I read in the issues people asked about it, so just installed that to ensure the perfectly working state, but I couldn't make it working.

**Comment by sqpp** [comment]
Based on the command, it seems

python-qt4 (4.12.1+dfsg-2) .

**Comment by saschaludwig** [comment]
I don't have any development machine at hand today, so just let's test what happens when you comment out the said line 71. Maybe there is another issue which is more verbose :)

**Comment by sqpp** [comment]
It must be because I am running a Virtual machine maybe, it just launched with commenting it out 🗡 

Whenever I try to enter to settings the same message comes up

**Comment by saschaludwig** [comment]
Yes, there is another statement that restores the cursor to be visible when you enter settings.
But I doubt it's because of the VM. I would guess it has something to do with a newer pyqt version than I used to develop the code.
I will have a look into this in the coming days.

**Comment by sqpp** [comment]
Yeah, exactly just found before seen your mesasge, everything is work now :)

**Comment by sqpp** [comment]
Thanks for your time and pretty much thank for your fast replies!!!

**Comment by saschaludwig** [comment]
To be fair: that place is written in a bad style. I shouldn't have used static integers that once mapped to the required cursors... I will fix that and use the correct named cursors :-D.
Now that you commented that out, the cursor does not vanish in full screen mode :)
But I hope you can live with this workaround until I fixed this.
I let you know when I changed it and when you could give it a try.

**Comment by sqpp** [comment]
Actually I am not doing anything, but I helped out a radio in Hungary so they can use this cool Python software for their fun. :)

I am not familiar withy Python at all, so I did everything with my earlier knowledge with Linux

Thanks for all the help.
