### ISSUE TITLE
Update Python tfor Ubuntu 22.04

### ISSUE THREAD

**Issue by mikeopensauce** [saschaludwig/OnAirScreen#54]
Hi Sascha
I've been using your clock for many year snow and have just updated my PC that it runs on and get an error asking for a module that doesn't exist.
I can't seem to work out how to either get the missing module or upgrade your code to use the newer python.

Do you have nay suggestions please?

Many thanks

Mike
Traceback (most recent call last):
  File "./start.py", line 43, in <module>
    from PyQt4.QtGui import QApplication, QWidget, QCursor, QPalette, QColorDialog, QColor, QShortcut, QKeySequence, QDialog, QLineEdit, QVBoxLayout, QLabel, QIcon, QPixmap
ImportError: No module named PyQt4.QtGui

**Comment by saschaludwig** [comment]
It seems you are missing pyqt5. You can install it with:
`sudo apt install python3-pyqt5`

**Comment by mikeopensauce** [comment]
Sorry Sascha, I hadn't realised you had updated the code for QT5. My apologies and thanks for the response.
Mike

**Comment by mikeopensauce** [comment]
Sorry but further to this, I've downloaded the latest version (and qt5) and it now gives me a different error. I'm not very good with Python and I'm not sure how to resolve this one.

Mike

root@logger1:/home/administrator/clock# ./start.py 
Traceback (most recent call last):
  File "/home/administrator/clock/./start.py", line 53, in <module>
    from mainscreen import Ui_MainScreen
ModuleNotFoundError: No module named 'mainscreen'root@logger1:/home/administrator/clock# ./start.py 
Traceback (most recent call last):
  File "/home/administrator/clock/./start.py", line 53, in <module>
    from mainscreen import Ui_MainScreen
ModuleNotFoundError: No module named 'mainscreen'

**Comment by Liebeg** [comment]
I tried it earlier today and got the same outcome

**Comment by saschaludwig** [comment]
You have to compile the UI files. You could try run `make`.

**Comment by mikeopensauce** [comment]
Thanks Sascha, I'll give it a go

**Comment by mikeopensauce** [comment]
Finally got there :)
sudo apt install qtbase5-dev qt5-qmake  pyqt5-dev-tools  python3-pip
make
Thanks Sasscha
