### ISSUE TITLE
Run Echos on Windows System?

### ISSUE THREAD

**Issue by sqpp** [saschaludwig/OnAirScreen#7]
Hey!

Is there any way to run these commands from a Windows PC? The network would be on local of course

We have tried this app, but didn't work 
https://github.com/PavelBansky/EchoTool

Maybe you have an idea how could we solve this?

On Linux works fine.

**Comment by saschaludwig** [comment]
Which commands?

You can run almost any standard linux command on windows, try WSL.
https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by sqpp** [comment]
Oh, totally forgot it. Thank you! I surely needed my coffee! :D

**Comment by saschaludwig** [comment]
For later reference: in the binary release I added oas_send.exe, a tool to send OnAirScreen commands from windows over the network.
