### ISSUE TITLE
GPIO pins on raspberry

### ISSUE THREAD

**Issue by saghi92** [saschaludwig/OnAirScreen#9]
Hi 
I've checked the python code in settings but i couldn't find any relations between the led's and the raspberry pins. for example when the mic is on, what raspberry gpio pin should be connected??
thanks

**Comment by kat5man** [comment]
OK Thanks.

**Comment by saschaludwig** [comment]
There is no glue code supplied in this repo. You have to write your own GPIO -> OnAirScreen helper. Your GPIO code simply has to send the proper commands via the API to the UDP port. That could be on the same system as the OnAirScreen is running, or on any other system in the network which is capable of sending UDP packets.

**Comment by kat5man** [comment]
OK Thanks

**Comment by saschaludwig** [comment]
@saghi92 you could simply combine https://www.raspberrypi.org/documentation/usage/gpio/python/README.md and follow the "button" example and use
sock.sendto(MESSAGE, (UDP_IP, UDP_PORT)) from https://wiki.python.org/moin/UdpCommunication

And you should be ready to go with GPIO Pins->OnAirScreen
